package com.whut.www.model;

public class ApplicationForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.uid
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.province
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.city
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.district
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.type
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.baseName
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String basename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a210;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a211;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A2_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a212;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a35;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a36;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a37;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a38;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a39;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a310;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a311;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a312;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_13
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a313;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_14
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a314;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_15
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a315;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_16
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a316;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_17
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a317;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_18
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a318;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_19
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a319;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_20
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a320;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_21
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a321;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_22
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a322;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_23
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a323;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_24
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a324;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A3_25
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a325;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a45;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a46;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a47;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a48;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a49;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a410;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a411;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A4_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a412;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_1_img1_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a51Img1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_1_img2_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a51Img2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_1_img3_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a51Img3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_1_img4_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a51Img4Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a52;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_form.A5_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String a53;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.id
     *
     * @return the value of application_form.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.id
     *
     * @param id the value for application_form.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.uid
     *
     * @return the value of application_form.uid
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.uid
     *
     * @param uid the value for application_form.uid
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.province
     *
     * @return the value of application_form.province
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.province
     *
     * @param province the value for application_form.province
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.city
     *
     * @return the value of application_form.city
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.city
     *
     * @param city the value for application_form.city
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.district
     *
     * @return the value of application_form.district
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.district
     *
     * @param district the value for application_form.district
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.type
     *
     * @return the value of application_form.type
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.type
     *
     * @param type the value for application_form.type
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.baseName
     *
     * @return the value of application_form.baseName
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getBasename() {
        return basename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.baseName
     *
     * @param basename the value for application_form.baseName
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setBasename(String basename) {
        this.basename = basename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_1
     *
     * @return the value of application_form.A2_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA21() {
        return a21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_1
     *
     * @param a21 the value for application_form.A2_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA21(String a21) {
        this.a21 = a21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_2
     *
     * @return the value of application_form.A2_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA22() {
        return a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_2
     *
     * @param a22 the value for application_form.A2_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA22(String a22) {
        this.a22 = a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_3
     *
     * @return the value of application_form.A2_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA23() {
        return a23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_3
     *
     * @param a23 the value for application_form.A2_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA23(String a23) {
        this.a23 = a23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_4
     *
     * @return the value of application_form.A2_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA24() {
        return a24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_4
     *
     * @param a24 the value for application_form.A2_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA24(String a24) {
        this.a24 = a24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_5
     *
     * @return the value of application_form.A2_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA25() {
        return a25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_5
     *
     * @param a25 the value for application_form.A2_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA25(String a25) {
        this.a25 = a25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_6
     *
     * @return the value of application_form.A2_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA26() {
        return a26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_6
     *
     * @param a26 the value for application_form.A2_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA26(String a26) {
        this.a26 = a26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_7
     *
     * @return the value of application_form.A2_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA27() {
        return a27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_7
     *
     * @param a27 the value for application_form.A2_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA27(String a27) {
        this.a27 = a27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_8
     *
     * @return the value of application_form.A2_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA28() {
        return a28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_8
     *
     * @param a28 the value for application_form.A2_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA28(String a28) {
        this.a28 = a28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_9
     *
     * @return the value of application_form.A2_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA29() {
        return a29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_9
     *
     * @param a29 the value for application_form.A2_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA29(String a29) {
        this.a29 = a29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_10
     *
     * @return the value of application_form.A2_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA210() {
        return a210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_10
     *
     * @param a210 the value for application_form.A2_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA210(String a210) {
        this.a210 = a210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_11
     *
     * @return the value of application_form.A2_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA211() {
        return a211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_11
     *
     * @param a211 the value for application_form.A2_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA211(String a211) {
        this.a211 = a211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A2_12
     *
     * @return the value of application_form.A2_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA212() {
        return a212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A2_12
     *
     * @param a212 the value for application_form.A2_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA212(String a212) {
        this.a212 = a212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_1
     *
     * @return the value of application_form.A3_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA31() {
        return a31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_1
     *
     * @param a31 the value for application_form.A3_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA31(String a31) {
        this.a31 = a31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_2
     *
     * @return the value of application_form.A3_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA32() {
        return a32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_2
     *
     * @param a32 the value for application_form.A3_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA32(String a32) {
        this.a32 = a32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_3
     *
     * @return the value of application_form.A3_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA33() {
        return a33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_3
     *
     * @param a33 the value for application_form.A3_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA33(String a33) {
        this.a33 = a33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_4
     *
     * @return the value of application_form.A3_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA34() {
        return a34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_4
     *
     * @param a34 the value for application_form.A3_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA34(String a34) {
        this.a34 = a34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_5
     *
     * @return the value of application_form.A3_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA35() {
        return a35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_5
     *
     * @param a35 the value for application_form.A3_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA35(String a35) {
        this.a35 = a35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_6
     *
     * @return the value of application_form.A3_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA36() {
        return a36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_6
     *
     * @param a36 the value for application_form.A3_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA36(String a36) {
        this.a36 = a36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_7
     *
     * @return the value of application_form.A3_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA37() {
        return a37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_7
     *
     * @param a37 the value for application_form.A3_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA37(String a37) {
        this.a37 = a37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_8
     *
     * @return the value of application_form.A3_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA38() {
        return a38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_8
     *
     * @param a38 the value for application_form.A3_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA38(String a38) {
        this.a38 = a38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_9
     *
     * @return the value of application_form.A3_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA39() {
        return a39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_9
     *
     * @param a39 the value for application_form.A3_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA39(String a39) {
        this.a39 = a39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_10
     *
     * @return the value of application_form.A3_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA310() {
        return a310;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_10
     *
     * @param a310 the value for application_form.A3_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA310(String a310) {
        this.a310 = a310;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_11
     *
     * @return the value of application_form.A3_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA311() {
        return a311;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_11
     *
     * @param a311 the value for application_form.A3_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA311(String a311) {
        this.a311 = a311;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_12
     *
     * @return the value of application_form.A3_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA312() {
        return a312;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_12
     *
     * @param a312 the value for application_form.A3_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA312(String a312) {
        this.a312 = a312;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_13
     *
     * @return the value of application_form.A3_13
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA313() {
        return a313;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_13
     *
     * @param a313 the value for application_form.A3_13
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA313(String a313) {
        this.a313 = a313;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_14
     *
     * @return the value of application_form.A3_14
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA314() {
        return a314;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_14
     *
     * @param a314 the value for application_form.A3_14
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA314(String a314) {
        this.a314 = a314;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_15
     *
     * @return the value of application_form.A3_15
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA315() {
        return a315;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_15
     *
     * @param a315 the value for application_form.A3_15
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA315(String a315) {
        this.a315 = a315;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_16
     *
     * @return the value of application_form.A3_16
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA316() {
        return a316;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_16
     *
     * @param a316 the value for application_form.A3_16
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA316(String a316) {
        this.a316 = a316;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_17
     *
     * @return the value of application_form.A3_17
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA317() {
        return a317;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_17
     *
     * @param a317 the value for application_form.A3_17
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA317(String a317) {
        this.a317 = a317;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_18
     *
     * @return the value of application_form.A3_18
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA318() {
        return a318;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_18
     *
     * @param a318 the value for application_form.A3_18
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA318(String a318) {
        this.a318 = a318;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_19
     *
     * @return the value of application_form.A3_19
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA319() {
        return a319;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_19
     *
     * @param a319 the value for application_form.A3_19
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA319(String a319) {
        this.a319 = a319;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_20
     *
     * @return the value of application_form.A3_20
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA320() {
        return a320;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_20
     *
     * @param a320 the value for application_form.A3_20
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA320(String a320) {
        this.a320 = a320;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_21
     *
     * @return the value of application_form.A3_21
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA321() {
        return a321;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_21
     *
     * @param a321 the value for application_form.A3_21
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA321(String a321) {
        this.a321 = a321;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_22
     *
     * @return the value of application_form.A3_22
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA322() {
        return a322;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_22
     *
     * @param a322 the value for application_form.A3_22
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA322(String a322) {
        this.a322 = a322;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_23
     *
     * @return the value of application_form.A3_23
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA323() {
        return a323;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_23
     *
     * @param a323 the value for application_form.A3_23
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA323(String a323) {
        this.a323 = a323;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_24
     *
     * @return the value of application_form.A3_24
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA324() {
        return a324;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_24
     *
     * @param a324 the value for application_form.A3_24
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA324(String a324) {
        this.a324 = a324;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A3_25
     *
     * @return the value of application_form.A3_25
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA325() {
        return a325;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A3_25
     *
     * @param a325 the value for application_form.A3_25
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA325(String a325) {
        this.a325 = a325;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_1
     *
     * @return the value of application_form.A4_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA41() {
        return a41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_1
     *
     * @param a41 the value for application_form.A4_1
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA41(String a41) {
        this.a41 = a41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_2
     *
     * @return the value of application_form.A4_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA42() {
        return a42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_2
     *
     * @param a42 the value for application_form.A4_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA42(String a42) {
        this.a42 = a42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_3
     *
     * @return the value of application_form.A4_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA43() {
        return a43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_3
     *
     * @param a43 the value for application_form.A4_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA43(String a43) {
        this.a43 = a43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_4
     *
     * @return the value of application_form.A4_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA44() {
        return a44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_4
     *
     * @param a44 the value for application_form.A4_4
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA44(String a44) {
        this.a44 = a44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_5
     *
     * @return the value of application_form.A4_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA45() {
        return a45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_5
     *
     * @param a45 the value for application_form.A4_5
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA45(String a45) {
        this.a45 = a45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_6
     *
     * @return the value of application_form.A4_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA46() {
        return a46;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_6
     *
     * @param a46 the value for application_form.A4_6
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA46(String a46) {
        this.a46 = a46;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_7
     *
     * @return the value of application_form.A4_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA47() {
        return a47;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_7
     *
     * @param a47 the value for application_form.A4_7
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA47(String a47) {
        this.a47 = a47;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_8
     *
     * @return the value of application_form.A4_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA48() {
        return a48;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_8
     *
     * @param a48 the value for application_form.A4_8
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA48(String a48) {
        this.a48 = a48;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_9
     *
     * @return the value of application_form.A4_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA49() {
        return a49;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_9
     *
     * @param a49 the value for application_form.A4_9
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA49(String a49) {
        this.a49 = a49;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_10
     *
     * @return the value of application_form.A4_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA410() {
        return a410;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_10
     *
     * @param a410 the value for application_form.A4_10
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA410(String a410) {
        this.a410 = a410;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_11
     *
     * @return the value of application_form.A4_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA411() {
        return a411;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_11
     *
     * @param a411 the value for application_form.A4_11
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA411(String a411) {
        this.a411 = a411;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A4_12
     *
     * @return the value of application_form.A4_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA412() {
        return a412;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A4_12
     *
     * @param a412 the value for application_form.A4_12
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA412(String a412) {
        this.a412 = a412;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_1_img1_id
     *
     * @return the value of application_form.A5_1_img1_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA51Img1Id() {
        return a51Img1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_1_img1_id
     *
     * @param a51Img1Id the value for application_form.A5_1_img1_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA51Img1Id(String a51Img1Id) {
        this.a51Img1Id = a51Img1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_1_img2_id
     *
     * @return the value of application_form.A5_1_img2_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA51Img2Id() {
        return a51Img2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_1_img2_id
     *
     * @param a51Img2Id the value for application_form.A5_1_img2_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA51Img2Id(String a51Img2Id) {
        this.a51Img2Id = a51Img2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_1_img3_id
     *
     * @return the value of application_form.A5_1_img3_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA51Img3Id() {
        return a51Img3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_1_img3_id
     *
     * @param a51Img3Id the value for application_form.A5_1_img3_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA51Img3Id(String a51Img3Id) {
        this.a51Img3Id = a51Img3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_1_img4_id
     *
     * @return the value of application_form.A5_1_img4_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA51Img4Id() {
        return a51Img4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_1_img4_id
     *
     * @param a51Img4Id the value for application_form.A5_1_img4_id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA51Img4Id(String a51Img4Id) {
        this.a51Img4Id = a51Img4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_2
     *
     * @return the value of application_form.A5_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA52() {
        return a52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_2
     *
     * @param a52 the value for application_form.A5_2
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA52(String a52) {
        this.a52 = a52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_form.A5_3
     *
     * @return the value of application_form.A5_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getA53() {
        return a53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_form.A5_3
     *
     * @param a53 the value for application_form.A5_3
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setA53(String a53) {
        this.a53 = a53;
    }
}