package com.whut.www.model;

public class BaseImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_image.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_image.url
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_image.id
     *
     * @return the value of base_image.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_image.id
     *
     * @param id the value for base_image.id
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_image.url
     *
     * @return the value of base_image.url
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_image.url
     *
     * @param url the value for base_image.url
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
}