package com.whut.www.dao;

import com.whut.www.model.ApplicationForm;
import com.whut.www.model.ApplicationFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    long countByExample(ApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int deleteByExample(ApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int insert(ApplicationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int insertSelective(ApplicationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    List<ApplicationForm> selectByExample(ApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    ApplicationForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") ApplicationForm record, @Param("example") ApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int updateByExample(@Param("record") ApplicationForm record, @Param("example") ApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int updateByPrimaryKeySelective(ApplicationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_form
     *
     * @mbg.generated Thu May 09 11:42:47 CST 2019
     */
    int updateByPrimaryKey(ApplicationForm record);
}