package com.whut.www.dao;

import com.whut.www.model.BaseImage;
import com.whut.www.model.BaseImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    long countByExample(BaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int deleteByExample(BaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int insert(BaseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int insertSelective(BaseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    List<BaseImage> selectByExample(BaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    BaseImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseImage record, @Param("example") BaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int updateByExample(@Param("record") BaseImage record, @Param("example") BaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int updateByPrimaryKeySelective(BaseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_image
     *
     * @mbg.generated Wed May 08 22:55:29 CST 2019
     */
    int updateByPrimaryKey(BaseImage record);
}